apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-demo
  name: docker-demo
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: docker-demo
  sessionAffinity: None
  type: ClusterIP
