# master config
MASTER_MEMORY = 2048
MASTER_CPUS = 1

# nodes config
NODE_COUNT = 3
NODE_MEMORY = 2048
NODE_CPUS = 1

BOX_IMAGE = "minimal/xenial64"

Vagrant.configure("2") do |config|

  # Master _______________________________________________________
  config.vm.define "master" do |masterconfig|
    masterconfig.vm.box = BOX_IMAGE
    masterconfig.vm.network :private_network, ip: "192.168.33.30"
    masterconfig.vm.hostname = "master"
  
    masterconfig.vm.provider "virtualbox" do |vb|
      vb.memory = MASTER_MEMORY
      vb.cpus = MASTER_CPUS
    end  

    masterconfig.vm.provision "shell" do |s|
      s.path = "./provision/setup.sh"
    end
  
	  masterconfig.vm.provision "shell" do |s|
      s.path = "./provision/setup-master.sh"
	  end
  end
  
  # Nodes _______________________________________________________
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |nodeconfig|
      nodeconfig.vm.box = BOX_IMAGE
      nodeconfig.vm.network :private_network, ip: "192.168.33.#{i + 30}"
      nodeconfig.vm.hostname = "node#{i}"
    
      nodeconfig.vm.provider "virtualbox" do |vb|
        vb.memory = NODE_MEMORY
        vb.cpus = NODE_CPUS
      end  

      nodeconfig.vm.provision "shell" do |s|
        s.path = "./provision/setup.sh"
      end
      
      nodeconfig.vm.provision "shell" do |s|
        s.path = "./provision/setup-node.sh"
      end
	  
    end

  end

end