# master config
MASTER_MEMORY = 1024
MASTER_CPUS = 1


BOX_IMAGE = "minimal/xenial64"

Vagrant.configure("2") do |config|

  # Master _______________________________________________________
  config.vm.define "master" do |masterconfig|
    masterconfig.vm.box = BOX_IMAGE
    masterconfig.vm.network :private_network, ip: "192.169.33.30"
    masterconfig.vm.hostname = "master"
  
    masterconfig.vm.provider "virtualbox" do |vb|
      vb.memory = MASTER_MEMORY
      vb.cpus = MASTER_CPUS
    end  

    masterconfig.vm.provision "shell" do |s|
      s.path = "./provision/setup.sh"
    end
  

  end
  


end