apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: docker-demo
  name: docker-demo
spec: 
  type: LoadBalancer
  ports: 
    - 
      name: docker-demo
      port: 8080
  selector: 
    app: docker-demo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  selector:
    matchLabels:
      app: docker-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - name: docker-demo
        image: ehazlett/docker-demo
        ports:
        - containerPort: 8080
          name: docker-demo
        env:
        - name: TITLE
          value: "Docker EE Demo"
        - name: SHOW_VERSION
          value: "true"
        - name: VERSION
          value: "1.0"